apiVersion: apps/v1
kind: Deployment
metadata:
  name: dock123-deployment
  labels:
    app: dock123
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dock123
  template:
    metadata:
      labels:
        app: dock123
    spec:
      containers:
      - name: dock123-container
        image: sandiriamulya/gitdocker:latest # Your Docker Hub image
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: dock123-config # Assuming you have a ConfigMap defined with this name
